services:
  # Frontend Service
  - type: web
    name: sellbridge-frontend
    env: node
    region: frankfurt
    plan: free
    buildCommand: cd frontend && yarn install && yarn build
    startCommand: cd frontend && npx serve -s build -l $PORT
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: REACT_APP_BACKEND_URL
        sync: false
    
  # Backend Service  
  - type: web
    name: sellbridge-backend
    env: python
    region: frankfurt
    plan: free
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MONGO_URL
        sync: false
      - key: DB_NAME
        value: sellbridge
